services:
  server-automation_portal_service:
    build: .
    container_name: server-automation_portal_service
    ports:
      - "3043:3043"
    env_file:
      - .env.prod
    environment:
      - NODE_ENV=production
    networks:
      - dass_private

networks:
  dass_private:
    external: true